In [2]:
BASE_URL = "https://api.91m.top/hero/v1"

In [3]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [4]:
## 数据更新
data1 = pd.read_csv('./data/matchList.csv')
data2 = pd.read_csv('./data/matchList_v2.csv')
data3 = pd.read_csv('./data/matchList_v3.csv')

In [5]:
data_final = pd.concat([data1,data2,data3],axis=0).drop_duplicates().reset_index(drop=True)
data_final['id'] = data_final.index

In [6]:
data_final.to_csv('./data/matchList_total.csv',index=False)

In [7]:
# $rowAcntCamp == 1 ? $myCamp = "蓝方" : $myCamp = "红方";
# 1：蓝方 // 2：红方

data_final.groupby(['acntCamp']).count()

,id,areaType,gameSvrId,relaySvrId,gameSeq,userId,roleId,playerId,winCamp,usedtime,...,camp_1_Hero_2,camp_1_Hero_3,camp_1_Hero_4,camp_2_Hero_0,camp_2_Hero_1,camp_2_Hero_2,camp_2_Hero_3,camp_2_Hero_4,jsonData,addTime
acntCamp,,,,,,,,,,,,,,,,,,,,,
1,157214,157214,157214,157214,157214,157214,157214,157214,157214,157214,...,157207,157207,157207,157207,157207,157207,157207,157207,0,157214
2,174289,174289,174289,174289,174289,174289,174289,174289,174289,174289,...,174287,174287,174287,174287,174287,174287,174287,174287,0,174289

In [8]:
157214 / (157214+174289)

0.4742460852541304

In [9]:
hero_data = pd.read_csv('./data/heroCombination.csv')

In [10]:
hero_id = pd.read_csv('./data/heroList.csv')
type_lst = pd.DataFrame([{1:'边',2:'中',3:'射',4:'野',5:'辅'}]).T
hero_id['position'] = hero_id['type_1'].apply(lambda x: type_lst.loc[x])
# hero_lst = hero_id[['heroId','heroName']].set_index('heroId')
hero_lst = hero_id[['heroId','heroName','position']].set_index('heroId')

In [11]:
hero_id

,id,type_1,type_2,type_3,heroId,heroName,eName,cName,rCD,gradient,...,trend,isUp,oldIndex,newIndex,changeValue,onlineTime,adjustmentTime,skinTime,updateTime,position
0,1,4,1.0,NaN,511,猪八戒,zhū_bā_jiè,八戒|猪头|悟能|二师兄|zbj,99,3.0,...,2.0,2,76,65,-0.002072,30/1/2019 00:00:00,27/6/2024 00:00:00,19/6/2023 00:00:00,11/8/2024 00:30:03,野
1,2,4,2.0,NaN,515,嫦娥,cháng_é,娥子|蛾子|ce,99,1.0,...,2.0,2,19,16,0.005411,16/1/2019 00:00:00,27/6/2024 00:00:00,25/1/2024 00:00:00,11/8/2024 00:30:03,野
2,3,1,NaN,NaN,510,孙策,sūn_cè,孙笨|船夫|sc,99,1.5,...,2.0,2,31,31,0.001919,17/7/2018 00:00:00,14/3/2024 00:00:00,23/5/2024 00:00:00,11/8/2024 00:30:03,边
3,4,4,1.0,NaN,198,梦奇,mèng_qí,肥猫|胖猫|胖达|荣荣|mq,99,4.0,...,0.0,0,97,104,-0.000459,23/10/2017 00:00:00,20/9/2023 00:00:00,NaN,11/8/2024 00:30:03,野
4,5,5,NaN,NaN,194,苏烈,sū_liè,核弹|玄武|大电池|sl,99,2.0,...,0.0,0,50,49,0.003549,26/9/2017 00:00:00,7/3/2024 00:00:00,30/5/2024 00:00:00,11/8/2024 00:30:03,辅
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,130,3,NaN,NaN,519,敖隐,áo_yǐn,熬隐|龙王|白龙马|ay,99,0.5,...,2.0,18,2,3,0.006069,1/1/1999 00:00:00,28/3/2024 00:00:00,NaN,11/8/2024 00:30:03,射
118,131,4,1.0,NaN,517,大司命,dà_sī_mìng,dsm,99,1.0,...,2.0,11,16,18,-0.002051,1/1/1999 00:00:00,27/6/2024 00:00:00,23/5/2024 00:00:00,11/8/2024 00:30:03,野
119,132,1,NaN,NaN,581,坦元,yuán_liú_zhī_zǐ___tǎn_kè,元流|源流|元流之子\_坦克|新英雄,99,3.5,...,0.0,1,58,70,0.001095,1/1/1999 00:00:00,NaN,NaN,11/8/2024 06:50:07,边
120,133,2,NaN,NaN,582,法元,yuán_liú_zhī_zǐ___fǎ_shī,元流|源流|元流之子\_法师|新英雄,99,1.5,...,2.0,0,29,29,0.005907,1/1/1999 00:00:00,NaN,NaN,11/8/2024 06:50:07,中
121,134,5,NaN,NaN,577,少司缘,shào_sī_yuán,缘神,99,10.0,...,NaN,0,1,1,0.000000,1/1/1999 00:00:00,NaN,NaN,11/8/2024 06:50:16,辅

In [12]:
hero_data[['Hero_1','position_1']] = hero_data['heroId_1'].apply(lambda x: hero_lst.loc[x])
hero_data[['Hero_2','position_2']] = hero_data['heroId_2'].apply(lambda x: hero_lst.loc[x])

In [13]:
hero_oppodata = hero_data[['Hero_1','position_1','Hero_2','position_2','opponentPickTimes','opponentPickRate', 'opponentWinTimes', 'opponentWinRate']]
# Win_rate_matrix = hero_oppodata[['Hero_1','Hero_2','opponentWinRate']].pivot(index='Hero_1',columns='Hero_2',values='opponentWinRate').fillna(0).round(4)

In [14]:
hero_oppo_jun =  hero_oppodata[hero_oppodata['position_1'] == '野']

In [15]:
hero_oppo_jun_edg =  hero_oppo_jun[hero_oppodata['position_2'] == '边']
hero_oppo_jun_jun =  hero_oppo_jun[hero_oppodata['position_2'] == '野']
hero_oppo_jun_mid =  hero_oppo_jun[hero_oppodata['position_2'] == '中']
hero_oppo_jun_sho =  hero_oppo_jun[hero_oppodata['position_2'] == '射']
hero_oppo_jun_ass =  hero_oppo_jun[hero_oppodata['position_2'] == '辅']

In [16]:
Win_matrix_jun_edg = hero_oppo_jun_edg[['Hero_1','Hero_2','opponentWinRate']].pivot(index='Hero_1',columns='Hero_2',values='opponentWinRate').fillna(0).round(4)
Win_matrix_jun_jun = hero_oppo_jun_jun[['Hero_1','Hero_2','opponentWinRate']].pivot(index='Hero_1',columns='Hero_2',values='opponentWinRate').fillna(0).round(4)
Win_matrix_jun_mid = hero_oppo_jun_mid[['Hero_1','Hero_2','opponentWinRate']].pivot(index='Hero_1',columns='Hero_2',values='opponentWinRate').fillna(0).round(4)
Win_matrix_jun_sho = hero_oppo_jun_sho[['Hero_1','Hero_2','opponentWinRate']].pivot(index='Hero_1',columns='Hero_2',values='opponentWinRate').fillna(0).round(4)
Win_matrix_jun_ass = hero_oppo_jun_ass[['Hero_1','Hero_2','opponentWinRate']].pivot(index='Hero_1',columns='Hero_2',values='opponentWinRate').fillna(0).round(4)

In [17]:
(Win_matrix_jun_sho == 0).sum().sum()

353

In [18]:
Win_matrix_jun_sho.shape[0] * Win_matrix_jun_sho.shape[1]

448

In [19]:
# hero_oppodata.to_excel('./result/胜率统计test.xlsx')

In [20]:
Match_data = pd.read_csv('./data/matchList_total.csv')

In [21]:
Match_data.columns

Index(['id', 'areaType', 'gameSvrId', 'relaySvrId', 'gameSeq', 'userId',
       'roleId', 'playerId', 'acntCamp', 'winCamp', 'usedtime', 'camp_1_Ban_0',
       'camp_1_Ban_1', 'camp_1_Ban_2', 'camp_1_Ban_3', 'camp_1_Ban_4',
       'camp_2_Ban_0', 'camp_2_Ban_1', 'camp_2_Ban_2', 'camp_2_Ban_3',
       'camp_2_Ban_4', 'camp_1_Hero_0', 'camp_1_Hero_1', 'camp_1_Hero_2',
       'camp_1_Hero_3', 'camp_1_Hero_4', 'camp_2_Hero_0', 'camp_2_Hero_1',
       'camp_2_Hero_2', 'camp_2_Hero_3', 'camp_2_Hero_4', 'jsonData',
       'addTime'],
      dtype='object')

In [22]:
Match_data.shape

(331503, 33)

In [23]:
Match_list = Match_data[['winCamp','camp_1_Hero_0', 'camp_1_Hero_1', 'camp_1_Hero_2','camp_1_Hero_3', 'camp_1_Hero_4', 'camp_2_Hero_0', 'camp_2_Hero_1','camp_2_Hero_2', 'camp_2_Hero_3', 'camp_2_Hero_4']]

In [24]:
Match_list = Match_list.applymap(lambda x:str(x))
Match_list = Match_list.applymap(lambda x:x.split(".")[0])

In [25]:
Match_list[Match_list['winCamp'] == '1'][['camp_1_Hero_0', 'camp_1_Hero_1', 'camp_1_Hero_2','camp_1_Hero_3', 'camp_1_Hero_4']]

       camp_1_Hero_0 camp_1_Hero_1 camp_1_Hero_2 camp_1_Hero_3 camp_1_Hero_4
3                519           190           191           126           514
5                518           196           312           537           171
6                199           502           564           194           141
11               518           197           548           510           118
14               154           190           191           519           171
...              ...           ...           ...           ...           ...
331493           150           149           510           196           127
331494           154           118           136           130           177
331495           150           148           139           133           114
331500           191           139           533           196           521
331502           196           149           523           153           517

[162451 rows x 5 columns]

In [26]:
Win_list = Match_list[Match_list['winCamp'] == '1'][['camp_1_Hero_0', 'camp_1_Hero_1', 'camp_1_Hero_2','camp_1_Hero_3', 'camp_1_Hero_4','camp_2_Hero_0', 'camp_2_Hero_1','camp_2_Hero_2', 'camp_2_Hero_3', 'camp_2_Hero_4']]

Win_list = Win_list.rename(columns={'camp_1_Hero_0':'win_1',
                         'camp_1_Hero_1':'win_2',
                         'camp_1_Hero_2':'win_3',
                         'camp_1_Hero_3':'win_4',
                         'camp_1_Hero_4':'win_5',
                         'camp_2_Hero_0':'lose_1',
                         'camp_2_Hero_1':'lose_2',
                         'camp_2_Hero_2':'lose_3',
                         'camp_2_Hero_3':'lose_4',
                         'camp_2_Hero_4':'lose_5',
                         })

In [27]:
Win_list2 = Match_list[Match_list['winCamp'] == '2'][['camp_1_Hero_0', 'camp_1_Hero_1', 'camp_1_Hero_2','camp_1_Hero_3', 'camp_1_Hero_4','camp_2_Hero_0', 'camp_2_Hero_1','camp_2_Hero_2', 'camp_2_Hero_3', 'camp_2_Hero_4']]

Win_list2 = Win_list2.rename(columns={'camp_2_Hero_0':'win_1',
                         'camp_2_Hero_1':'win_2',
                         'camp_2_Hero_2':'win_3',
                         'camp_2_Hero_3':'win_4',
                         'camp_2_Hero_4':'win_5',
                         'camp_1_Hero_0':'lose_1',
                         'camp_1_Hero_1':'lose_2',
                         'camp_1_Hero_2':'lose_3',
                         'camp_1_Hero_3':'lose_4',
                         'camp_1_Hero_4':'lose_5',
                         })

In [28]:
Win_list_final = pd.concat([Win_list,Win_list2])

In [29]:
Win_list_final

       win_1 win_2 win_3 win_4 win_5 lose_1 lose_2 lose_3 lose_4 lose_5
3        519   190   191   126   514    129    577    139    152    111
5        518   196   312   537   171    159    153    111    197    130
6        199   502   564   194   141    577    518    527    152    169
11       518   197   548   510   118    159    519    533    139    521
14       154   190   191   519   171    518    127    149    514    548
...      ...   ...   ...   ...   ...    ...    ...    ...    ...    ...
331496   518   582   162   174   534    519    129    159    182    149
331497   518   577   513   149   155    502    521    126    111    505
331498   149   518   140   155   186    127    517    118    564    524
331499   199   152   149   518   113    157    179    548    137    120
331501   149   518   137   148   169    577    182    183    133    510

[331503 rows x 10 columns]

In [30]:
Win_list_final.dropna(how='any')

       win_1 win_2 win_3 win_4 win_5 lose_1 lose_2 lose_3 lose_4 lose_5
3        519   190   191   126   514    129    577    139    152    111
5        518   196   312   537   171    159    153    111    197    130
6        199   502   564   194   141    577    518    527    152    169
11       518   197   548   510   118    159    519    533    139    521
14       154   190   191   519   171    518    127    149    514    548
...      ...   ...   ...   ...   ...    ...    ...    ...    ...    ...
331496   518   582   162   174   534    519    129    159    182    149
331497   518   577   513   149   155    502    521    126    111    505
331498   149   518   140   155   186    127    517    118    564    524
331499   199   152   149   518   113    157    179    548    137    120
331501   149   518   137   148   169    577    182    183    133    510

[331503 rows x 10 columns]

In [31]:
def combination_win_rate(hero1,hero2):
    id1 = hero_lst[hero_lst['heroName'] == hero1].index[0]
    id2 = hero_lst[hero_lst['heroName'] == hero2].index[0]
    win_games = Win_list_final[(Win_list_final[['win_1','win_2','win_3','win_4','win_5']] == str(id1)).any(axis=1) & (Win_list_final[['win_1','win_2','win_3','win_4','win_5']] == str(id2)).any(axis=1)].shape[0]
    lose_games = Win_list_final[(Win_list_final[['lose_1','lose_2','lose_3','lose_4','lose_5']] == str(id1)).any(axis=1) & (Win_list_final[['lose_1','lose_2','lose_3','lose_4','lose_5']] == str(id2)).any(axis=1)].shape[0]
    return win_games / (win_games+lose_games), win_games+lose_games

In [32]:
# pos1_name = '边'
# pos2_name = '辅'

# pos1_lst = hero_lst[hero_lst['position'] == pos1_name]['heroName'].values
# pos2_lst = hero_lst[hero_lst['position'] == pos2_name]['heroName'].values


# pos1_pos2_win_matrix = pd.DataFrame()
# pos1_pos2_games_matrix = pd.DataFrame()

# for pos1 in pos1_lst:
#     for pos2 in pos2_lst:
#         rate, games = combination_win_rate(pos1,pos2)
#         pos1_pos2_win_matrix.loc[pos1,pos2] = rate
#         pos1_pos2_games_matrix.loc[pos1,pos2] = games

In [34]:
sho_ass_matrix = pd.concat([sho_ass_win_matrix.unstack().to_frame(),
sho_ass_games_matrix.unstack().to_frame()],axis=1)
sho_ass_matrix.columns = ['胜率','胜场']

NameError: name 'sho_ass_win_matrix' is not defined

In [35]:
sho_ass_matrix[(sho_ass_matrix['胜场'] >= 2500) & (sho_ass_matrix['胜率'] >= 0.52)].sort_values(by='胜率',ascending=False)

NameError: name 'sho_ass_matrix' is not defined

In [36]:
sho_ass_win_matrix

NameError: name 'sho_ass_win_matrix' is not defined

In [37]:
combination_win_rate('马可波罗','瑶')

(0.46779126888497546, 10789)

In [38]:
combination_win_rate('朵莉亚','亚连')

(0.4847545947468488, 14201)

In [39]:
pos_lst = hero_lst['position']
pos_lst.index = [str(x) for x in pos_lst.index]

heroname_lst = hero_lst['heroName']
heroname_lst.index = [str(x) for x in heroname_lst.index]

In [40]:
def index2pos(id):
    try:
        return pos_lst[id]
    except:
        return '无'
    
def index2heroname(id):
    try:
        return heroname_lst[id]
    except:
        return '无'

In [41]:
Win_list_postion = Win_list_final.applymap(index2pos)
Win_list_heroname = Win_list_final.applymap(index2heroname)

In [42]:
Win_list_postion.groupby(by=['win_1','win_2','win_3']).count().sort_values(by='lose_4',ascending=False).head(50)

                   win_4  win_5  lose_1  lose_2  lose_3  lose_4  lose_5
win_1 win_2 win_3
射     野     中       8565   8565    8565    8565    8565    8565    8565
辅     野     中       8073   8073    8073    8073    8073    8073    8073
野     中     射       7852   7852    7852    7852    7852    7852    7852
            边       7740   7740    7740    7740    7740    7740    7740
      边     中       7680   7680    7680    7680    7680    7680    7680
      射     中       7585   7585    7585    7585    7585    7585    7585
      辅     中       7456   7456    7456    7456    7456    7456    7456
射     野     辅       7287   7287    7287    7287    7287    7287    7287
            边       7149   7149    7149    7149    7149    7149    7149
辅     野     射       7125   7125    7125    7125    7125    7125    7125
野     辅     射       6811   6811    6811    6811    6811    6811    6811
辅     野     边       6709   6709    6709    6709    6709    6709    6709
射     中     野       6648   6648    6648    6648    6648    6648    6648
野     中     辅       6551   6551    6551    6551    6551    6551    6551
射     辅     野       6380   6380    6380    6380    6380    6380    6380
辅     中     野       6356   6356    6356    6356    6356    6356    6356
野     边     射       6216   6216    6216    6216    6216    6216    6216
中     野     边       6208   6208    6208    6208    6208    6208    6208
野     辅     边       6183   6183    6183    6183    6183    6183    6183
中     野     射       6162   6162    6162    6162    6162    6162    6162
辅     射     野       6147   6147    6147    6147    6147    6147    6147
野     射     边       6103   6103    6103    6103    6103    6103    6103
            辅       6072   6072    6072    6072    6072    6072    6072
      边     辅       5576   5576    5576    5576    5576    5576    5576
中     野     辅       5421   5421    5421    5421    5421    5421    5421
辅     边     野       5375   5375    5375    5375    5375    5375    5375
射     边     野       5107   5107    5107    5107    5107    5107    5107
中     射     野       4933   4933    4933    4933    4933    4933    4933
辅     射     中       4891   4891    4891    4891    4891    4891    4891
射     辅     中       4870   4870    4870    4870    4870    4870    4870
辅     边     中       4709   4709    4709    4709    4709    4709    4709
      中     边       4678   4678    4678    4678    4678    4678    4678
中     辅     野       4582   4582    4582    4582    4582    4582    4582
射     中     边       4560   4560    4560    4560    4560    4560    4560
边     野     中       4551   4551    4551    4551    4551    4551    4551
射     辅     边       4547   4547    4547    4547    4547    4547    4547
辅     中     射       4510   4510    4510    4510    4510    4510    4510
中     边     野       4422   4422    4422    4422    4422    4422    4422
射     边     中       4408   4408    4408    4408    4408    4408    4408
      中     辅       4268   4268    4268    4268    4268    4268    4268
辅     射     边       4179   4179    4179    4179    4179    4179    4179
      边     射       4079   4079    4079    4079    4079    4079    4079
射     边     辅       3680   3680    3680    3680    3680    3680    3680
边     野     射       3623   3623    3623    3623    3623    3623    3623
      中     野       3621   3621    3621    3621    3621    3621    3621
中     射     边       3334   3334    3334    3334    3334    3334    3334
      边     射       3333   3333    3333    3333    3333    3333    3333
      辅     射       3241   3241    3241    3241    3241    3241    3241
            边       3235   3235    3235    3235    3235    3235    3235
      射     辅       3091   3091    3091    3091    3091    3091    3091

In [43]:
Win_list_heroname.groupby(by=['win_1','win_2','win_3']).count().sort_values(by='lose_4',ascending=False).head(50)

                   win_4  win_5  lose_1  lose_2  lose_3  lose_4  lose_5
win_1 win_2 win_3
朵莉亚   亚连    甄姬       112    112     112     112     112     112     112
      甄姬    亚连        88     88      88      88      88      88      88
马超    孙膑    甄姬        84     84      84      84      84      84      84
朵莉亚   亚连    孙尚香       81     81      81      81      81      81      81
不知火舞  马超    孙膑        80     80      80      80      80      80      80
马超    甄姬    孙膑        78     78      78      78      78      78      78
敖隐    马超    孙膑        73     73      73      73      73      73      73
马超    甄姬    亚连        69     69      69      69      69      69      69
朵莉亚   亚连    宫本武藏      68     68      68      68      68      68      68
马超    百里守约  甄姬        67     67      67      67      67      67      67
朵莉亚   亚连    杨玉环       66     66      66      66      66      66      66
敖隐    马超    甄姬        65     65      65      65      65      65      65
朵莉亚   亚连    百里守约      65     65      65      65      65      65      65
      马超    亚连        65     65      65      65      65      65      65
敖隐    朵莉亚   亚连        64     64      64      64      64      64      64
马超    甄姬    孙尚香       64     64      64      64      64      64      64
      孙膑    亚连        64     64      64      64      64      64      64
公孙离   马超    瑶         63     63      63      63      63      63      63
马超    亚连    孙膑        63     63      63      63      63      63      63
敖隐    大司命   甄姬        62     62      62      62      62      62      62
马超    甄姬    百里守约      61     61      61      61      61      61      61
朵莉亚   亚连    嫦娥        61     61      61      61      61      61      61
敖隐    马超    张飞        61     61      61      61      61      61      61
马超    孙膑    百里守约      60     60      60      60      60      60      60
朵莉亚   敖隐    亚连        60     60      60      60      60      60      60
敖隐    甄姬    张飞        59     59      59      59      59      59      59
马超    孙膑    戈娅        59     59      59      59      59      59      59
朵莉亚   亚连    狄仁杰       59     59      59      59      59      59      59
公孙离   甄姬    张飞        59     59      59      59      59      59      59
马超    甄姬    老夫子       58     58      58      58      58      58      58
      孙膑    老夫子       58     58      58      58      58      58      58
      百里守约  孙膑        57     57      57      57      57      57      57
      甄姬    张飞        57     57      57      57      57      57      57
敖隐    甄姬    老夫子       56     56      56      56      56      56      56
            大司命       55     55      55      55      55      55      55
马超    杨玉环   孙膑        55     55      55      55      55      55      55
      孙膑    狄仁杰       54     54      54      54      54      54      54
敖隐    马超    亚连        54     54      54      54      54      54      54
马超    孙膑    杨玉环       53     53      53      53      53      53      53
不知火舞  朵莉亚   亚连        53     53      53      53      53      53      53
敖隐    大司命   孙膑        53     53      53      53      53      53      53
马超    孙尚香   甄姬        53     53      53      53      53      53      53
朵莉亚   亚连    西施        53     53      53      53      53      53      53
马超    孙膑    白起        52     52      52      52      52      52      52
            孙尚香       52     52      52      52      52      52      52
      孙尚香   孙膑        51     51      51      51      51      51      51
朵莉亚   亚连    裴擒虎       51     51      51      51      51      51      51
      裴擒虎   亚连        51     51      51      51      51      51      51
马超    朵莉亚   亚连        51     51      51      51      51      51      51
敖隐    甄姬    裴擒虎       50     50      50      50      50      50      50

In [44]:
Win_lst_all = pd.DataFrame()
for win in ['win_1','win_2','win_3','win_4','win_5']:
    for lose in ['lose_1','lose_2','lose_3','lose_4','lose_5']:
        Win_lst = Win_list_final[[win,lose]]
        Win_lst.columns = ['win', 'lose']
        Win_lst_all = pd.concat([Win_lst_all, Win_lst])

In [45]:
Win_lst_all_ally = pd.DataFrame()
for win1 in range(5-1):
    for win2 in range(win1+1,5):
        Win_lst = Win_list_final[[['win_1','win_2','win_3','win_4','win_5'][win1],['win_1','win_2','win_3','win_4','win_5'][win2]]]
        Win_lst.columns = ['ally1', 'ally2']
        Win_lst_all_ally = pd.concat([Win_lst_all_ally, Win_lst])

Lose_lst_all_ally = pd.DataFrame()
for lose1 in range(5-1):
    for lose2 in range(lose1+1,5):
        Lose_lst = Win_list_final[[['lose_1','lose_2','lose_3','lose_4','lose_5'][lose1],['lose_1','lose_2','lose_3','lose_4','lose_5'][lose2]]]
        Lose_lst.columns = ['ally1', 'ally2']
        Lose_lst_all_ally = pd.concat([Lose_lst_all_ally, Lose_lst])

In [46]:
Win_lst_all['games'] = 1

In [47]:
Win_lst_all_ally['games'] = 1
Lose_lst_all_ally['games'] = 1

In [48]:
Win_lst_ally = Win_lst_all_ally.groupby(['ally1', 'ally2']).count().reset_index().iloc[:-1]
Lose_lst_ally = Lose_lst_all_ally.groupby(['ally1', 'ally2']).count().reset_index().iloc[:-1]

In [49]:
Win_ally_matrix = Win_lst_ally.pivot(index='ally1',columns='ally2',values='games').fillna(0)
Lose_ally_matrix = Lose_lst_ally.pivot(index='ally1',columns='ally2',values='games').fillna(0)

In [50]:
Win_ally_matrix =  Win_ally_matrix + Win_ally_matrix.T
Lose_ally_matrix = Lose_ally_matrix + Lose_ally_matrix.T

In [51]:
Win_lst_final = Win_lst_all.groupby(['win','lose']).count().reset_index().iloc[:-1]

In [52]:
Win_games_matrix = Win_lst_final.pivot(index='win',columns='lose',values='games').fillna(0)

In [53]:
hero_name_lst = hero_lst.reset_index().sort_values(by='heroId')['heroName'].values

In [54]:
Win_rate_matrix = Win_games_matrix.div(Win_games_matrix + Win_games_matrix.T)
Win_rate_matrix = Win_rate_matrix.fillna(0).round(4)

In [55]:
Win_rate_ally_matrix = Win_ally_matrix.div(Win_ally_matrix + Lose_ally_matrix)
Win_rate_ally_matrix = Win_rate_ally_matrix.fillna(0).round(4)

In [56]:
Win_games_matrix.index = hero_name_lst 
Win_games_matrix.columns = hero_name_lst 

Win_rate_matrix.index = hero_name_lst 
Win_rate_matrix.columns = hero_name_lst 

Win_ally_matrix.index = hero_name_lst 
Win_ally_matrix.columns = hero_name_lst 

Lose_ally_matrix.index = hero_name_lst 
Lose_ally_matrix.columns = hero_name_lst

Win_rate_ally_matrix.index = hero_name_lst 
Win_rate_ally_matrix.columns = hero_name_lst

In [57]:
## 胜率根据胜场进行调整
# adj_rate_oppo = np.sqrt(np.sqrt((Win_games_matrix + Win_games_matrix.T)/(Win_games_matrix + Win_games_matrix.T).max().max()))
# adj_rate_ally = np.sqrt(np.sqrt((Win_ally_matrix + Lose_ally_matrix)/(Win_ally_matrix + Lose_ally_matrix).max().max()))

adj_rate_oppo = (Win_games_matrix + Win_games_matrix.T)/(Win_games_matrix + Win_games_matrix.T).max().max()
adj_rate_ally = (Win_ally_matrix + Lose_ally_matrix)/(Win_ally_matrix + Lose_ally_matrix).max().max()

In [58]:
Win_rate_matrix_adj = 0.5 + (Win_rate_matrix - 0.5) * adj_rate_oppo
Win_rate_ally_matrix_adj = 0.5 + (Win_rate_ally_matrix - 0.5) * adj_rate_ally

In [76]:
pos_lst = hero_lst[hero_lst['position'] == '野']['heroName'].values

## 根据胜场惩罚得到的最新推荐系统
edg_lst = hero_lst[hero_lst['position'] == '边']['heroName'].values
jun_lst = hero_lst[hero_lst['position'] == '野']['heroName'].values
mid_lst = hero_lst[hero_lst['position'] == '中']['heroName'].values
sho_lst = hero_lst[hero_lst['position'] == '射']['heroName'].values
ass_lst = hero_lst[hero_lst['position'] == '辅']['heroName'].values

In [77]:
def hero_commendation(allys=['公孙离','少司缘'], enemys=['马可波罗','瑶'], pos=None, adj=None):
    if pos:
        try:
            pos_lst = hero_lst[hero_lst['position'] == pos]['heroName'].values

            if adj:
                Win_matrix = Win_rate_matrix_adj.loc[pos_lst]
                Win_matrix_ally = Win_rate_ally_matrix_adj.loc[pos_lst]
            else:
                Win_matrix = Win_rate_matrix.loc[pos_lst]
                Win_matrix_ally = Win_rate_ally_matrix.loc[pos_lst]
            res = pd.concat([Win_matrix_ally[allys],Win_matrix[enemys]],axis=1).mean(axis=1).loc[pos_lst].sort_values(ascending=False).head(5)
            res = res.to_frame('win_rate').reset_index()
        except:
            pass
    else:
        if adj:
            Win_matrix = Win_rate_matrix_adj
            Win_matrix_ally = Win_rate_ally_matrix_adj
        else:
            Win_matrix = Win_rate_matrix
            Win_matrix_ally = Win_rate_ally_matrix

        edg_res = pd.concat([Win_matrix_ally[allys],Win_matrix[enemys]],axis=1).mean(axis=1).loc[edg_lst].sort_values(ascending=False).head(5)
        jun_res = pd.concat([Win_matrix_ally[allys],Win_matrix[enemys]],axis=1).mean(axis=1).loc[jun_lst].sort_values(ascending=False).head(5)
        mid_res = pd.concat([Win_matrix_ally[allys],Win_matrix[enemys]],axis=1).mean(axis=1).loc[mid_lst].sort_values(ascending=False).head(5)
        sho_res = pd.concat([Win_matrix_ally[allys],Win_matrix[enemys]],axis=1).mean(axis=1).loc[sho_lst].sort_values(ascending=False).head(5)
        ass_res = pd.concat([Win_matrix_ally[allys],Win_matrix[enemys]],axis=1).mean(axis=1).loc[ass_lst].sort_values(ascending=False).head(5)

        edg_res = edg_res.to_frame('win_rate').reset_index()
        edg_res.insert(0,'position','边')
        jun_res = jun_res.to_frame('win_rate').reset_index()
        jun_res.insert(0,'position','野')
        mid_res = mid_res.to_frame('win_rate').reset_index()
        mid_res.insert(0,'position','中')
        sho_res = sho_res.to_frame('win_rate').reset_index()
        sho_res.insert(0,'position','射')
        ass_res = ass_res.to_frame('win_rate').reset_index()
        ass_res.insert(0,'position','辅')

        res = pd.concat([edg_res,jun_res,mid_res,sho_res,ass_res],axis=0).set_index(['position','index'])
    return res

In [136]:
hero_pos_lst = hero_lst.set_index('heroName')

hero_pos_lst.loc[hero_name_lst[0]]

position    辅
Name: 廉颇, dtype: object

In [193]:
recommend_ally = pd.DataFrame()
recommend_counter = pd.DataFrame()

for name in hero_name_lst:
    pos = hero_pos_lst.loc[name].values[0]

    recommend_ally_res = pd.DataFrame({
        '英雄名':name,\
        '分路':pos,\
        '边':Win_rate_ally_matrix_adj.loc[name].loc[edg_lst].sort_values(ascending=False).head(5).index,\
        '野':Win_rate_ally_matrix_adj.loc[name].loc[jun_lst].sort_values(ascending=False).head(5).index,\
        '中':Win_rate_ally_matrix_adj.loc[name].loc[mid_lst].sort_values(ascending=False).head(5).index,\
        '射':Win_rate_ally_matrix_adj.loc[name].loc[sho_lst].sort_values(ascending=False).head(5).index,\
        '辅':Win_rate_ally_matrix_adj.loc[name].loc[ass_lst].sort_values(ascending=False).head(5).index
        })

    recommend_ally_res[pos] = '-'

    recommend_counter_res = pd.DataFrame({
        '英雄名':name,\
        '分路':pos,\
        '边':Win_rate_matrix_adj.loc[name].loc[edg_lst].sort_values(ascending=True).head(5).index,\
        '野':Win_rate_matrix_adj.loc[name].loc[jun_lst].sort_values(ascending=True).head(5).index,\
        '中':Win_rate_matrix_adj.loc[name].loc[mid_lst].sort_values(ascending=True).head(5).index,\
        '射':Win_rate_matrix_adj.loc[name].loc[sho_lst].sort_values(ascending=True).head(5).index,\
        '辅':Win_rate_matrix_adj.loc[name].loc[ass_lst].sort_values(ascending=True).head(5).index
        })
    
    recommend_ally = pd.concat([recommend_ally, recommend_ally_res]).dropna(how='any')
    recommend_counter = pd.concat([recommend_counter, recommend_counter_res]).dropna(how='any')

recommend_ally = recommend_ally.sort_values(by='分路',ascending=False).set_index(['分路','英雄名'])
recommend_counter = recommend_counter.sort_values(by='分路',ascending=False).set_index(['分路','英雄名'])

In [194]:
recommend_ally.sort_index(ascending=False).to_excel('recommend_ally.xlsx')
recommend_counter.sort_index(ascending=False).to_excel('recommend_counter.xlsx')

In [101]:
Win_rate_ally_matrix_adj.loc['嫦娥'].loc[edg_lst].sort_values(ascending=False).head(7)

# 和镜组队胜率高的英雄：
# 老夫子、程咬金、孙策、蒙恬、刘邦
# 甄姬、海月、西施、不知火舞、武则天
# 戈娅、蒙犽、公孙离、百里守约、敖隐
# 张飞、墨子、少司缘、大乔、庄周

# 和嫦娥组队胜率高的英雄：
# 老夫子、亚连、孙策、蒙恬、花木兰
# 甄姬、西施、不知火舞、杨玉环、王昭君
# 戈娅、蒙犽、孙尚香、百里守约、敖隐
# 张飞、墨子、少司缘、孙膑、苏烈

老夫子    0.517473
亚连     0.509645
花木兰    0.508416
孙策     0.507222
元歌     0.504777
蒙恬     0.504207
关羽     0.503897
Name: 嫦娥, dtype: float64

In [230]:
# Win_rate_matrix[['鲁班七号']].loc[pos_lst].mean(1).sort_values(ascending=False)

In [231]:
# jun_sho_matrix = Win_rate_matrix.loc[hero_lst[hero_lst['position'] == '野']['heroName'].values][hero_lst[hero_lst['position'] == '射']['heroName'].values]

# jun_sho_matrix.to_excel('jun_sho_winrate.xlsx')

In [1]:
hero_commendation(['马可波罗','瑶','大司命','王昭君'],['孙尚香','甄姬','镜','吕布','朵莉亚'])

NameError: name 'hero_commendation' is not defined

In [237]:
hero_commendation(['公孙离','孙膑'],['虞姬','张飞'],adj=True)

                win_rate
position index
边        老夫子    0.515678
         亚连     0.506612
         蒙恬     0.506054
         白起     0.505675
         孙策     0.505651
野        马超     0.519528
         嫦娥     0.509148
         雅典娜    0.506345
         镜      0.504830
         云中君    0.503165
中        甄姬     0.518879
         西施     0.508144
         不知火舞   0.507331
         貂蝉     0.506502
         杨玉环    0.506367
射        戈娅     0.511004
         蒙犽     0.508879
         敖隐     0.507090
         公孙离    0.504565
         孙尚香    0.502918
辅        孙膑     0.506426
         少司缘    0.506079
         大乔     0.503758
         苏烈     0.502745
         明世隐    0.502646

In [122]:
hero_commendation(['公孙离','马超'],['马可波罗','瑶','夏侯惇','貂蝉','白起'],'野')

马超      0.508354
嫦娥      0.507501
镜       0.503424
阿古朵     0.502984
雅典娜     0.502858
百里玄策    0.502486
云中君     0.502129
裴擒虎     0.501347
司马懿     0.501156
诸葛亮     0.501125
兰陵王     0.500842
露娜      0.500602
韩信      0.500503
阿轲      0.500486
钟无艳     0.500473
典韦      0.500286
盘古      0.500162
李白      0.500123
暃       0.500114
梦奇      0.500001
dtype: float64

In [115]:
Win_games_matrix.to_excel('./result/Win_games_matrix.xlsx')

In [116]:
Win_rate_matrix.to_excel('./result/Win_rate_matrix.xlsx')

In [117]:
Win_rate_stack = Win_rate_matrix.stack().reset_index()
Win_rate_stack.columns = ['英雄名称','对位英雄','胜率']

Win_games_stack = Win_games_matrix.stack().reset_index()
Win_games_stack.columns = ['英雄名称','对位英雄','胜场']

In [118]:
Win_rate_stack = Win_rate_stack.merge(Win_games_stack)

In [119]:
Win_rate_stack.to_excel('./result/Win_games_list.xlsx')

In [121]:
Win_rate_stack

      英雄名称 对位英雄      胜率      胜场
0       廉颇   廉颇  0.0000     0.0
1       廉颇   小乔  0.4828   631.0
2       廉颇   赵云  0.5897    69.0
3       廉颇   墨子  0.5087   821.0
4       廉颇   妲己  0.4744   102.0
...    ...  ...     ...     ...
14879   法元   海诺  0.5307   415.0
14880   法元  姬小满  0.4831   587.0
14881   法元  少司缘  0.4454  1163.0
14882   法元   坦元  0.4994   829.0
14883   法元   法元  0.0000     0.0

[14884 rows x 4 columns]

In [123]:
hero_commendation(['鲁班七号'],['安琪拉','大乔','澜','亚连'],'野')

马超      0.508979
嫦娥      0.504589
镜       0.504165
百里玄策    0.502695
雅典娜     0.502338
兰陵王     0.501802
云中君     0.501446
诸葛亮     0.501405
韩信      0.501269
司马懿     0.501039
露娜      0.500677
李白      0.500538
钟无艳     0.500526
曹操      0.500464
曜       0.500289
阿轲      0.500254
裴擒虎     0.500010
盘古      0.500003
梦奇      0.499982
赵云      0.499945
dtype: float64

In [ ]:
hero_commendation(['鲁班七号'],['安琪拉','大乔','澜','亚连'],'野')

In [ ]:
Win_games_matrix

,廉颇,小乔,赵云,墨子,妲己,嬴政,孙尚香,鲁班七号,庄周,刘禅,...,金蝉,暃,赵怀真,莱西奥,戈娅,海诺,姬小满,少司缘,坦元,法元
廉颇,0.0,631.0,69.0,821.0,102.0,130.0,1928.0,378.0,337.0,281.0,...,88.0,339.0,127.0,192.0,988.0,233.0,436.0,685.0,482.0,794.0
小乔,676.0,0.0,69.0,936.0,162.0,142.0,2346.0,389.0,261.0,290.0,...,84.0,468.0,148.0,256.0,1259.0,336.0,576.0,1020.0,583.0,1102.0
赵云,48.0,68.0,0.0,81.0,15.0,9.0,196.0,47.0,26.0,24.0,...,10.0,35.0,12.0,33.0,101.0,39.0,44.0,80.0,50.0,86.0
墨子,793.0,1039.0,110.0,0.0,191.0,183.0,2852.0,598.0,591.0,388.0,...,138.0,584.0,136.0,287.0,1411.0,389.0,645.0,1302.0,827.0,1230.0
妲己,113.0,153.0,12.0,146.0,0.0,14.0,341.0,69.0,50.0,70.0,...,16.0,77.0,22.0,36.0,213.0,58.0,91.0,141.0,76.0,119.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
海诺,248.0,302.0,35.0,374.0,50.0,60.0,867.0,207.0,131.0,118.0,...,23.0,157.0,60.0,85.0,479.0,0.0,178.0,318.0,228.0,367.0
姬小满,484.0,548.0,38.0,652.0,96.0,115.0,1729.0,308.0,255.0,210.0,...,58.0,340.0,94.0,163.0,903.0,216.0,0.0,682.0,427.0,628.0
少司缘,906.0,1166.0,117.0,1324.0,208.0,223.0,3418.0,759.0,388.0,394.0,...,145.0,640.0,212.0,367.0,1790.0,501.0,762.0,0.0,915.0,1448.0
坦元,537.0,670.0,61.0,686.0,95.0,114.0,1909.0,395.0,317.0,263.0,...,66.0,370.0,125.0,183.0,933.0,216.0,382.0,778.0,0.0,831.0
法元,753.0,929.0,96.0,1051.0,153.0,166.0,2704.0,519.0,296.0,304.0,...,112.0,490.0,178.0,265.0,1371.0,415.0,587.0,1163.0,829.0,0.0

In [ ]:
Win_rate_matrix.loc['坦元'].sort_values(ascending=False).head(10)

澜      0.6114
李元芳    0.5664
妲己     0.5556
刘禅     0.5549
亚瑟     0.5548
赵云     0.5495
程咬金    0.5459
杨戬     0.5412
后羿     0.5402
项羽     0.5400
Name: 坦元, dtype: float64

In [ ]:
Win_rate_sort = Win_rate_stack.sort_values(by = '胜率',ascending=False)

In [ ]:
Win_rate_sort[(Win_rate_sort['胜场'] >= 1000) & (Win_rate_sort['胜率'] >= 0.52)].groupby('英雄名称').count().sort_values(by='胜场',ascending=False).head(10)

      对位英雄  胜率  胜场
英雄名称
马超      44  44  44
甄姬      44  44  44
戈娅      41  41  41
老夫子     36  36  36
少司缘     31  31  31
西施      30  30  30
孙膑      28  28  28
蒙犽      26  26  26
嫦娥      24  24  24
镜       24  24  24

In [ ]:
pos_lst = hero_lst[hero_lst['position'] == '中']['heroName'].values

res_df = pd.concat([Win_rate_matrix.loc[pos_lst].mean(axis=1), Win_games_matrix.loc[pos_lst].sum(axis=1)], axis = 1)
res_df = res_df.rename(columns={0:'胜率',1:'胜场'})
res_df = res_df.sort_values(by='胜率', ascending=False)
res_df.to_excel('./win_rate_role1_role2/win_rate_stat_edg.xlsx')

In [ ]:
pos_lst = hero_lst[hero_lst['position'] == '射']['heroName'].values
Win_rate_matrix.loc[pos_lst].mean(axis=1).sort_values(ascending=False).to_frame()

             0
戈娅    0.536477
公孙离   0.526443
蒙犽    0.522357
鲁班七号  0.508818
伽罗    0.502290
敖隐    0.498820
百里守约  0.497029
成吉思汗  0.496647
孙尚香   0.495016
后羿    0.493390
黄忠    0.491412
狄仁杰   0.491103
莱西奥   0.489243
艾琳    0.480398
虞姬    0.479701
李元芳   0.478642
马可波罗  0.471308

In [ ]:
# def counter_query()

Win_rate_sort.query("(英雄名称=='刘备')&(对位英雄=='孙悟空')")

     英雄名称 对位英雄      胜率    胜场
6639   刘备  孙悟空  0.6279  27.0

In [ ]:
[
len(hero_lst[hero_lst['position'] == '边']['heroName'].values),
len(hero_lst[hero_lst['position'] == '野']['heroName'].values),
len(hero_lst[hero_lst['position'] == '中']['heroName'].values),
len(hero_lst[hero_lst['position'] == '射']['heroName'].values),
len(hero_lst[hero_lst['position'] == '辅']['heroName'].values)
]

[23, 34, 25, 17, 23]

In [ ]:
23*22*34*33*25*24*17*16*23*22 / 2

23441427187200.0

In [ ]:
# counter_data = pd.read_excel('./result/英雄对抗优劣势表.xlsx')